// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/OctopusJazzNightPoster-Y2mfib/JazzNightPoster.tsx": () => import("../components/mockups/templates/OctopusJazzNightPoster-Y2mfib/JazzNightPoster.tsx")
};
